<?php

namespace AppBundle\Repository;

/**
 * ImportantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportantRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllImportant()
  {
    return $this->createQueryBuilder('i')
      ->orderBy('i.niveau', 'DESC')
      ->getQuery()
      ->getResult()
    ;
  }
}
