<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTodo()
  {
    return $this->createQueryBuilder('t')
      ->innerJoin('t.important', 'i')
      ->where('t.fait = false')
      ->addOrderBy('i.niveau', 'DESC')
      ->addOrderBy('t.dateLimite', 'ASC')
      ->getQuery()
      ->getResult()
    ;
  }
  
  public function findDone()
  {
    return $this->createQueryBuilder('t')
      ->innerJoin('t.important', 'i')
      ->where('t.fait = true')
      ->addOrderBy('i.niveau', 'DESC')
      ->addOrderBy('t.dateLimite', 'ASC')
      ->getQuery()
      ->getResult()
    ;
  }
}
